baseURL = 'https://monkeywave.github.io'
languageCode = 'en-us'
title = 'Just a monkey working with bits and bytes'
theme = "hugo-theme-tailwind"

[params]
  author = "Daniel Baier"
  description = "A blog chronicling the adventure of exploring bits and bytes, uncovering the digital depths behind everyday technology."
  github = "monkeywave"  # Optional
  twitter = "danielbaier"   # Optional

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[markup]
  [markup.highlight]
    style = "github"

[module]
  [[module.imports]]
    path = "github.com/tomowang/hugo-theme-tailwind"