baseURL = "https://monkeywave.github.io"
languageCode = "en"
title = "Just a monkey working with bits and bytes"
copyright = "Daniel Baier"
pagination.pagerSize = 10
author = "Daniel Baier"
theme = "tailwind"


[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20